

services:

  # --------- CONTROLLER ---------
  controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    container_name: ansible-controller
    hostname: controller
    networks:
      - ansiblenet
    volumes:
      - ./ansible:/ansible
    tty: true

  # --------- NODES (all build from same Dockerfile.node, using build cache) ---------

  node1:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node1
    hostname: node1
    networks:
      - ansiblenet

  node2:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node2
    hostname: node2
    networks:
      - ansiblenet

  node3:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node3
    hostname: node3
    networks:
      - ansiblenet

  node4:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node4
    hostname: node4
    networks:
      - ansiblenet

  node5:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node5
    hostname: node5
    networks:
      - ansiblenet

  node6:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node6
    hostname: node6
    networks:
      - ansiblenet

  node7:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node7
    hostname: node7
    networks:
      - ansiblenet

  node8:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node8
    hostname: node8
    networks:
      - ansiblenet

  node9:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node9
    hostname: node9
    networks:
      - ansiblenet

  node10:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node10
    hostname: node10
    networks:
      - ansiblenet

networks:
  ansiblenet:
    driver: bridge
